export type Provider = 'claude' | 'deepseek' | 'openai' | 'openrouter'

export type Mode = 'hosted' | 'byok'

export const DEFAULT_BACKEND_URL = 'http://localhost:8787'

export interface LlmSettings {
  mode: Mode
  backendUrl: string
  provider: Provider
  apiKey: string
  model: string
}

export const DEFAULT_MODELS: Record<Provider, string> = {
  claude: 'claude-sonnet-4-5',
  deepseek: 'deepseek-chat',
  openai: 'gpt-4o-mini',
  openrouter: 'openai/gpt-4o-mini',
}

export const PROVIDER_LABELS: Record<Provider, string> = {
  claude: 'Claude (Anthropic)',
  deepseek: 'DeepSeek',
  openai: 'OpenAI',
  openrouter: 'OpenRouter',
}

// ── Folders & videos ─────────────────────────────────────────────────────

export interface Folder {
  id: string
  name: string
  videoIds: string[]
  createdAt: string
}

export interface VideoRef {
  videoId: string
  url: string
  title: string
  channel: string
  thumbnail: string
  addedAt: string
}

export interface VideoMeta {
  videoId: string
  url: string
  title: string
  channel: string
  thumbnail: string
}

export interface TranscriptResult {
  meta: VideoMeta
  transcript: string
  isAutoGenerated: boolean
}

// ── Knowledge dataset (per video) ────────────────────────────────────────

export interface VideoDataset {
  videoId: string
  transcript: string
  notes: string
  provider: Provider | 'hosted'
  model: string
  generatedAt: string
}

// ── Quiz cards (per folder) ──────────────────────────────────────────────

export interface QuizCard {
  id: string
  videoId: string
  question: string
  answer: string
  createdAt: string
}

// ── Teacher mode: folder skills + chat ───────────────────────────────────

export interface FolderSkills {
  folderId: string
  content: string
  sourceVideoIds: string[]
  updatedAt: string
}

export interface ChatAttachment {
  name: string
  text: string
}

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  content: string
  attachments?: ChatAttachment[]
  createdAt: string
}

// ── Auto-generation pipeline (dataset + skills, run after capture) ──────

// 'failed' is terminal — the pipeline never auto-retries it. The user must
// explicitly retry (RETRY_PIPELINE_JOB), which re-queues it.
export type PipelineJobStatus = 'queued' | 'extracting' | 'generating' | 'done' | 'failed'

export interface PipelineJob {
  videoId: string
  folderId: string
  title: string
  status: PipelineJobStatus
  error?: string
}
