// Opens a YouTube video in a background tab just long enough to extract its
// transcript via the content script, then closes the tab. Used whenever the
// caller isn't already on that video's tab (the notebook page, or the
// auto-generation pipeline processing videos added from elsewhere).

const TAB_LOAD_TIMEOUT_MS = 15_000

function waitForTabComplete(tabId: number): Promise<void> {
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      chrome.tabs.onUpdated.removeListener(listener)
      reject(new Error('Timed out waiting for the video page to load.'))
    }, TAB_LOAD_TIMEOUT_MS)

    function listener(updatedTabId: number, info: chrome.tabs.TabChangeInfo) {
      if (updatedTabId === tabId && info.status === 'complete') {
        clearTimeout(timeout)
        chrome.tabs.onUpdated.removeListener(listener)
        resolve()
      }
    }
    chrome.tabs.onUpdated.addListener(listener)
  })
}

export interface TranscriptExtractionResult {
  ok: boolean
  meta?: unknown
  transcript?: string
  isAutoGenerated?: boolean
  error?: string
}

const SEND_MESSAGE_RETRIES = 4
const SEND_MESSAGE_RETRY_DELAY_MS = 400

// chrome.tabs.sendMessage races the content script's own startup: the tab
// firing "complete" doesn't guarantee the content script has finished
// evaluating and registered its chrome.runtime.onMessage listener yet
// (slower page loads, heavier scripts, or just scheduling jitter can widen
// this gap). When the listener isn't ready yet, Chrome rejects with
// "Could not establish connection. Receiving end does not exist." — that
// specific failure is transient and safe to retry; anything else (e.g. the
// content script's own handler throwing) is not.
function isReceivingEndMissing(err: unknown): boolean {
  return err instanceof Error && err.message.includes('Receiving end does not exist')
}

async function sendMessageWithRetry(
  tabId: number,
  message: unknown,
): Promise<TranscriptExtractionResult> {
  let lastErr: unknown
  for (let attempt = 0; attempt <= SEND_MESSAGE_RETRIES; attempt++) {
    try {
      return (await chrome.tabs.sendMessage(tabId, message)) as TranscriptExtractionResult
    } catch (err) {
      lastErr = err
      if (!isReceivingEndMissing(err) || attempt === SEND_MESSAGE_RETRIES) throw err
      await new Promise((r) => setTimeout(r, SEND_MESSAGE_RETRY_DELAY_MS))
    }
  }
  // Unreachable — the loop above always returns or throws.
  throw lastErr instanceof Error ? lastErr : new Error('Failed to message content script.')
}

export async function extractTranscriptInBackgroundTab(url: string): Promise<TranscriptExtractionResult> {
  const tab = await chrome.tabs.create({ url, active: false })
  if (!tab.id) return { ok: false, error: 'Failed to open a background tab for extraction.' }

  try {
    await waitForTabComplete(tab.id)
    // The content script runs at document_end; give it a brief moment to
    // register its message listener after the "complete" event fires. This
    // is just a head start — sendMessageWithRetry covers the case where
    // it's still not enough.
    await new Promise((r) => setTimeout(r, 500))
    return await sendMessageWithRetry(tab.id, { type: 'EXTRACT_TRANSCRIPT' })
  } catch (err) {
    // Log the real cause for debugging, but never surface raw connection/
    // messaging errors to the user — they're meaningless outside this file.
    console.error('extractTranscriptInBackgroundTab failed:', err)
    const message = isReceivingEndMissing(err)
      ? "This video's page took too long to load. Try again in a moment."
      : 'Failed to extract transcript from the video page. Try again in a moment.'
    return { ok: false, error: message }
  } finally {
    chrome.tabs.remove(tab.id).catch(() => {})
  }
}
