import { useEffect, useState } from 'react'
import { defaultModelFor, getSettings, saveSettings } from '../lib/storage'
import { PROVIDER_LABELS } from '../types'
import type { Mode, Provider } from '../types'

const PROVIDERS: Provider[] = ['claude', 'deepseek', 'openai', 'openrouter']

const API_KEY_PLACEHOLDERS: Record<Provider, string> = {
  claude: 'sk-ant-…',
  deepseek: 'sk-…',
  openai: 'sk-…',
  openrouter: 'sk-or-…',
}

const PROVIDER_SENDS_TO: Record<Provider, string> = {
  claude: 'Anthropic',
  deepseek: 'DeepSeek',
  openai: 'OpenAI',
  openrouter: 'OpenRouter',
}

export default function SettingsPanel() {
  const [mode, setMode] = useState<Mode>('hosted')
  const [backendUrl, setBackendUrl] = useState('')
  const [provider, setProvider] = useState<Provider>('claude')
  const [apiKey, setApiKey] = useState('')
  const [model, setModel] = useState('')
  const [loading, setLoading] = useState(true)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    getSettings().then((s) => {
      setMode(s.mode)
      setBackendUrl(s.backendUrl)
      setProvider(s.provider)
      setApiKey(s.apiKey)
      setModel(s.model)
      setLoading(false)
    })
  }, [])

  function handleProviderChange(next: Provider) {
    setProvider(next)
    setModel(defaultModelFor(next))
  }

  async function handleSave() {
    await saveSettings({
      mode,
      backendUrl: backendUrl.trim(),
      provider,
      apiKey: apiKey.trim(),
      model: model.trim() || defaultModelFor(provider),
    })
    setSaved(true)
    setTimeout(() => setSaved(false), 1500)
  }

  if (loading) {
    return <div className="p-10 text-gray-400">Loading…</div>
  }

  return (
    <div className="max-w-lg mx-auto py-10 px-6 space-y-5">
      <h1 className="text-xl font-bold text-gray-900">Settings</h1>

      <div className="flex gap-1.5 bg-gray-100 rounded-full p-1 w-fit">
        {(['hosted', 'byok'] as Mode[]).map((m) => (
          <button
            key={m}
            type="button"
            onClick={() => setMode(m)}
            className={`text-xs px-4 py-1.5 rounded-full font-semibold transition-colors ${
              mode === m ? 'bg-white text-blue-600 shadow-sm' : 'text-gray-500 hover:text-gray-700'
            }`}
          >
            {m === 'hosted' ? 'Free (hosted)' : 'My own API key'}
          </button>
        ))}
      </div>

      {mode === 'hosted' ? (
        <>
          <p className="text-sm text-gray-500 leading-relaxed">
            Notes, quiz cards, skills, and teacher-mode chat are generated by Anchor's free hosted
            service, picking a random free model each time. No account or API key needed.
            Best-effort — free models can be slower or rate-limited during peak use.
          </p>
          <details className="text-sm">
            <summary className="cursor-pointer text-blue-500 font-semibold">
              Advanced: custom backend URL
            </summary>
            <label htmlFor="backend-url" className="sr-only">Backend URL</label>
            <input
              id="backend-url"
              type="text"
              value={backendUrl}
              onChange={(e) => setBackendUrl(e.target.value)}
              placeholder="https://your-anchor-backend.example.com"
              className="mt-2 w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-300"
            />
          </details>
        </>
      ) : (
        <>
          <div>
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">Provider</p>
            <div className="flex flex-wrap gap-1.5">
              {PROVIDERS.map((p) => (
                <button
                  key={p}
                  type="button"
                  onClick={() => handleProviderChange(p)}
                  className={`text-xs px-3 py-1.5 rounded-full font-semibold transition-colors ${
                    provider === p
                      ? 'bg-blue-500 text-white'
                      : 'bg-white border border-gray-200 text-gray-500 hover:bg-gray-50'
                  }`}
                >
                  {PROVIDER_LABELS[p]}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label htmlFor="api-key" className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">
              API key
            </label>
            <input
              id="api-key"
              type="password"
              value={apiKey}
              onChange={(e) => setApiKey(e.target.value)}
              placeholder={API_KEY_PLACEHOLDERS[provider]}
              className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-300"
            />
          </div>

          <div>
            <label htmlFor="model" className="block text-xs font-bold text-gray-400 uppercase tracking-widest mb-2">
              Model
            </label>
            <input
              id="model"
              type="text"
              value={model}
              onChange={(e) => setModel(e.target.value)}
              placeholder={defaultModelFor(provider)}
              className="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-300"
            />
          </div>

          <p className="text-xs text-gray-400 leading-relaxed">
            Your API key is stored locally in this browser and sent only to{' '}
            {PROVIDER_SENDS_TO[provider]} directly when generating content.
          </p>
        </>
      )}

      <button
        type="button"
        onClick={() => void handleSave()}
        className="px-5 py-2.5 bg-blue-500 hover:bg-blue-600 text-white text-sm font-bold rounded-full transition-colors shadow-sm"
      >
        {saved ? 'Saved ✓' : 'Save'}
      </button>
    </div>
  )
}
